- hosts: all
  tasks:
    - include_role:
        name: fetch-sphinx-tarball
      when: zuul_success | bool

    - name: Fetch archive
      fetch:
        dest: "{{ zuul.executor.work_root }}"
        src: "{{ ansible_user_dir }}/zuul-output/logs/docs-html.tar.gz"
        flat: "true"
      when: zuul_success | bool

- hosts: localhost
  roles:
    - role: upload-otc-docs
      artifact_src: "{{ zuul.executor.work_root }}/docs-html.tar.gz"
      when: zuul_success | bool
