- hosts: localhost
  roles:
    - role: emit-job-header
      zuul_log_path_shard_build: true
    - log-inventory

  tasks:
    - include_role: name=start-zuul-console
    - block:
        # A regular VM way
        - include_role: name=validate-host
        - include_role: name=prepare-workspace
        - include_role: name=add-build-sshkey
      when: "ansible_connection != 'kubectl'"
    - block:
        # A Pod way
        - include_role: name=prepare-workspace-openshift
        - include_role: name=remove-zuul-sshkey
      run_once: true
      when: "ansible_connection == 'kubectl'"
    
    - import_role: name=ensure-output-dirs
      when: ansible_user_dir is defined

